name: CI Pipeline

on:
  push:
  pull_request:

jobs:
  shellcheck:
    name: ShellCheck Scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Lint Shell Scripts
        run: shellcheck scripts/*.sh

  yamllint:
    name: YAML Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install yamllint
        run: sudo apt-get update && sudo apt-get install -y yamllint

      - name: Lint Elasticsearch YAML
        run: yamllint --strict configs/elasticsearch.yml

      - name: Lint Kibana YAML
        run: yamllint --strict configs/kibana.yml

  terraform:
    name: Terraform Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Format Check
        run: |
          cd terraform
          terraform fmt -check

      - name: Terraform Validate
        run: |
          cd terraform
          terraform validate

  ansible-lint:
    name: Ansible Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get remove -y ansible-core ansible
          sudo apt-get install -y ansible-core

      - name: Install ansible-lint
        run: sudo apt-get install -y ansible-lint

      - name: Lint Ansible Playbook
        run: |
          cd ansible
          ansible-lint playbook.yml
