name: CI Pipeline

on:
  push:
  pull_request:

jobs:
  shellcheck:
    name: ShellCheck Scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      - name: Lint Shell Scripts
        run: shellcheck scripts/*.sh

  yamllint:
    name: YAML Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install yamllint & dos2unix
        run: sudo apt-get update && sudo apt-get install -y yamllint dos2unix
      - name: Locate elasticsearch.yml
        id: find_config
        run: |
          CONFIG_PATH=$(find . -type f -name elasticsearch.yml | head -n1)
          if [ -z "$CONFIG_PATH" ]; then
            echo "Error: elasticsearch.yml not found" >&2
            exit 1
          fi
          echo "config_path=$CONFIG_PATH" >> $GITHUB_OUTPUT
      - name: Normalize line endings
        run: dos2unix "${{ steps.find_config.outputs.config_path }}"
      - name: Lint Elasticsearch YAML
        run: yamllint --strict "${{ steps.find_config.outputs.config_path }}"

  terraform:
    name: Terraform Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
      - name: Terraform Init
        run: |
          cd terraform
          terraform init -backend=false
      - name: Terraform Format Check
        run: |
          cd terraform
          terraform fmt -check
      - name: Terraform Validate
        run: |
          cd terraform
          terraform validate

  ansible-lint:
    name: Ansible Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python and pip
        run: sudo apt-get update && sudo apt-get install -y python3-pip
      - name: Install Ansible Core and ansible-lint via pip
        run: |
          pip3 install --upgrade pip
          pip3 install ansible-core ansible-lint
      - name: Install required Ansible collections
        run: |
          ansible-galaxy collection install community.general
      - name: Lint Ansible Playbook
        run: |
          cd ansible
          ansible-lint playbook.yml
