name: CI Pipeline

on: [push, pull_request]

jobs:
  # 1. Debug
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "--- ROOT DIR ---"
          ls -R .
          echo "--- configs ---"
          ls -l configs
          echo "--- scripts ---"
          ls -l scripts
          echo "--- terraform ---"
          ls -l terraform
          echo "--- ansible ---"
          ls -l ansible

  # 2. ShellCheck
  shellcheck:
    needs: debug
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update && sudo apt-get install -y shellcheck
      - run: |
          if ls scripts/*.sh; then
            shellcheck scripts/*.sh
          else
            echo "No shell scripts found!" && exit 1
          fi

  # 3. YAMLlint
  yamllint:
    needs: debug
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update && sudo apt-get install -y yamllint
      - run: |
          yamllint --strict configs/elasticsearch.yml
          yamllint --strict configs/kibana.yml

  # 4. Terraform Validate
  terraform-validate:
    needs: debug
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
      - run: |
          cd terraform
          terraform fmt -check
          terraform validate

  # 5. Ansible-lint
  ansible-lint:
    needs: debug
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update && sudo apt-get install -y ansible-lint
      - run: |
          cd ansible
          if [ -f playbook.yml ]; then
            ansible-lint playbook.yml
          else
            echo "playbook.yml missing!" && exit 1
          fi
