name: CI Pipeline

on:
  push:
  pull_request:

jobs:

  # 1. Debug: list all files and dirs
  debug:
    name: Debug Workspace
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List workspace
        run: |
          echo "Workspace root:"
          ls -R .

  shellcheck:
    name: ShellCheck Scripts
    runs-on: ubuntu-latest
    needs: debug
    steps:
      - uses: actions/checkout@v3

      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Lint Shell Scripts
        run: shellcheck scripts/*.sh

  yamllint:
    name: YAML Linting
    runs-on: ubuntu-latest
    needs: debug
    steps:
      - uses: actions/checkout@v3

      - name: Install yamllint
        run: sudo apt-get update && sudo apt-get install -y yamllint

      - name: Lint Elasticsearch YAML
        run: yamllint --strict configs/elasticsearch.yml

      - name: Lint Kibana YAML
        run: yamllint --strict configs/kibana.yml

  terraform:
    name: Terraform Validation
    runs-on: ubuntu-latest
    needs: debug
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Format Check
        run: |
          cd terraform
          pwd
          ls -l
          terraform fmt -check

      - name: Terraform Validate
        run: |
          cd terraform
          terraform validate

  ansible-lint:
    name: Ansible Linting
    runs-on: ubuntu-latest
    needs: debug
    steps:
      - uses: actions/checkout@v3

      - name: Install ansible-lint
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible-lint

      - name: Lint Ansible Playbook
        run: |
          cd ansible
          pwd
          ls -l
          ansible-lint playbook.yml
